import { readFileSync } from "node:fs";
import { strict as assert } from "node:assert";

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const api = read("deploy/k8s/base/api-deployment.yaml");
const worker = read("deploy/k8s/base/automation-deployment.yaml");
const config = read("deploy/k8s/base/configmap.yaml");
const kustomization = read("deploy/k8s/base/kustomization.yaml");
const networkPolicy = read("deploy/k8s/base/network-policy.yaml");
const secret = read("deploy/k8s/base/secret.example.yaml");
const hpa = read("deploy/k8s/base/api-hpa.yaml");
const apiPdb = read("deploy/k8s/base/api-pdb.yaml");
const workerPdb = read("deploy/k8s/base/automation-pdb.yaml");
const dockerfile = read("Dockerfile");
const workerDockerfile = read("apps/automation-worker/Dockerfile");
const count = (text, value) => text.split(value).length - 1;
const has = (text, pattern) => assert.match(text, pattern);

has(api, /replicas: 2/);
has(api, /maxUnavailable: 0/);
has(api, /path: \/api\/ready/);
has(api, /path: \/api\/live/);
has(api, /fieldPath: metadata\.name/);
has(api, /runAsNonRoot: true/);
has(api, /readOnlyRootFilesystem: true/);
has(api, /name: hyeboard-api/);
assert(!api.includes(":latest"));
assert(!worker.includes(":latest"));
assert(api.includes("replace-with-release-tag"));
assert(worker.includes("replace-with-release-tag"));
assert(config.includes("HYEB_SHUTDOWN_TIMEOUT_MS: \"30000\""));
has(hpa, /minReplicas: 2/);
has(hpa, /maxReplicas: 12/);
has(hpa, /averageUtilization: 70/);
has(apiPdb, /minAvailable: 1/);
has(workerPdb, /minAvailable: 1/);
has(dockerfile, /ENTRYPOINT \["node", "dist\/index\.js"\]/);
has(workerDockerfile, /ENTRYPOINT \["node", "dist\/cli\.cjs"\]/);
has(worker, /replicas: 2/);
has(worker, /path: \/readyz/);
has(worker, /path: \/healthz/);
has(worker, /AUTOMATION_CONSUMER_NAME/);
has(worker, /AUTOMATION_CONTROL_CONSUMER_NAME/);
has(worker, /BROWSERLESS_TOKEN/);
has(config, /HYEB_HA_MODE: distributed/);
has(config, /AUTOMATION_EXECUTION_MODE: distributed/);
has(config, /AUTOMATION_BROWSER_PROVIDER: browserless/);
assert(kustomization.includes("api-deployment.yaml"));
assert(kustomization.includes("automation-deployment.yaml"));
assert(!kustomization.includes("newTag: latest"));
assert(config.includes('HYEB_AUTOMATION_EXECUTOR_READY: "false"'));
assert(secret.includes("replace-with"));
assert(!/eyJ[A-Za-z0-9_-]{20,}/.test(secret));
has(networkPolicy, /name: hyeboard-automation-worker/);
assert(networkPolicy.includes("policyTypes:\n    - Egress"));
assert(count(api, "secretKeyRef:") >= 5);
assert(count(worker, "secretKeyRef:") >= 5);

console.log("Kubernetes manifest contract passed.");
